[package]
name = "online_game"
version = "0.1.0"
authors = ["Eoan <patriotrosii2019@mail.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2", features = ["full"] }
console = "0.11.3"
